#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate.Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Real_Estate")]
	public partial class Real_EstateDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public Real_EstateDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Real_EstateConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Real_EstateDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Real_EstateDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Real_EstateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Real_EstateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Location> Locations
		{
			get
			{
				return this.GetTable<Location>();
			}
		}
		
		public System.Data.Linq.Table<Image> Images
		{
			get
			{
				return this.GetTable<Image>();
			}
		}
		
		public System.Data.Linq.Table<RealEstate> RealEstates
		{
			get
			{
				return this.GetTable<RealEstate>();
			}
		}
		
		public System.Data.Linq.Table<Poperty> Poperties
		{
			get
			{
				return this.GetTable<Poperty>();
			}
		}
		
		public System.Data.Linq.Table<RealEstate_Description> RealEstate_Descriptions
		{
			get
			{
				return this.GetTable<RealEstate_Description>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Location")]
	public partial class Location
	{
		
		private int _id;
		
		private System.Nullable<int> _property_id;
		
		private string _location_name_eng;
		
		private string _location_name_vie;
		
		private string _status;
		
		public Location()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_property_id", DbType="Int")]
		public System.Nullable<int> property_id
		{
			get
			{
				return this._property_id;
			}
			set
			{
				if ((this._property_id != value))
				{
					this._property_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_name_eng", DbType="NVarChar(100)")]
		public string location_name_eng
		{
			get
			{
				return this._location_name_eng;
			}
			set
			{
				if ((this._location_name_eng != value))
				{
					this._location_name_eng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_name_vie", DbType="NVarChar(100)")]
		public string location_name_vie
		{
			get
			{
				return this._location_name_vie;
			}
			set
			{
				if ((this._location_name_vie != value))
				{
					this._location_name_vie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Image")]
	public partial class Image
	{
		
		private int _id;
		
		private System.Nullable<int> _real_estate_id;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private string _link_image;
		
		private System.Nullable<System.DateTime> _last_update;
		
		public Image()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_real_estate_id", DbType="Int")]
		public System.Nullable<int> real_estate_id
		{
			get
			{
				return this._real_estate_id;
			}
			set
			{
				if ((this._real_estate_id != value))
				{
					this._real_estate_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link_image", DbType="NVarChar(100)")]
		public string link_image
		{
			get
			{
				return this._link_image;
			}
			set
			{
				if ((this._link_image != value))
				{
					this._link_image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_update", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_update
		{
			get
			{
				return this._last_update;
			}
			set
			{
				if ((this._last_update != value))
				{
					this._last_update = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RealEstate")]
	public partial class RealEstate
	{
		
		private int _id;
		
		private System.Nullable<int> _location_id;
		
		private string _title_eng;
		
		private string _title_vie;
		
		private string _price;
		
		private string _code;
		
		private string _size;
		
		private string _floor;
		
		private string _view;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<int> _bathroom;
		
		private System.Nullable<int> _bedroom;
		
		private string _furniture;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _last_update;
		
		private System.Nullable<double> _numofviews;
		
		public RealEstate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_id", DbType="Int")]
		public System.Nullable<int> location_id
		{
			get
			{
				return this._location_id;
			}
			set
			{
				if ((this._location_id != value))
				{
					this._location_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title_eng", DbType="NVarChar(150)")]
		public string title_eng
		{
			get
			{
				return this._title_eng;
			}
			set
			{
				if ((this._title_eng != value))
				{
					this._title_eng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title_vie", DbType="NVarChar(150)")]
		public string title_vie
		{
			get
			{
				return this._title_vie;
			}
			set
			{
				if ((this._title_vie != value))
				{
					this._title_vie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="NVarChar(50)")]
		public string price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NChar(10)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this._code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="NChar(10)")]
		public string size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this._size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_floor", DbType="NChar(10)")]
		public string floor
		{
			get
			{
				return this._floor;
			}
			set
			{
				if ((this._floor != value))
				{
					this._floor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[view]", Storage="_view", DbType="NVarChar(50)")]
		public string view
		{
			get
			{
				return this._view;
			}
			set
			{
				if ((this._view != value))
				{
					this._view = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="Date")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bathroom", DbType="Int")]
		public System.Nullable<int> bathroom
		{
			get
			{
				return this._bathroom;
			}
			set
			{
				if ((this._bathroom != value))
				{
					this._bathroom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedroom", DbType="Int")]
		public System.Nullable<int> bedroom
		{
			get
			{
				return this._bedroom;
			}
			set
			{
				if ((this._bedroom != value))
				{
					this._bedroom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_furniture", DbType="NVarChar(50)")]
		public string furniture
		{
			get
			{
				return this._furniture;
			}
			set
			{
				if ((this._furniture != value))
				{
					this._furniture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_update", DbType="Date")]
		public System.Nullable<System.DateTime> last_update
		{
			get
			{
				return this._last_update;
			}
			set
			{
				if ((this._last_update != value))
				{
					this._last_update = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numofviews", DbType="Float")]
		public System.Nullable<double> numofviews
		{
			get
			{
				return this._numofviews;
			}
			set
			{
				if ((this._numofviews != value))
				{
					this._numofviews = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Poperty")]
	public partial class Poperty
	{
		
		private int _id;
		
		private int _parent_id;
		
		private string _name_eng;
		
		private string _name_vie;
		
		private string _status;
		
		public Poperty()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="Int NOT NULL")]
		public int parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this._parent_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_eng", DbType="NVarChar(100)")]
		public string name_eng
		{
			get
			{
				return this._name_eng;
			}
			set
			{
				if ((this._name_eng != value))
				{
					this._name_eng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_vie", DbType="NVarChar(100)")]
		public string name_vie
		{
			get
			{
				return this._name_vie;
			}
			set
			{
				if ((this._name_vie != value))
				{
					this._name_vie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RealEstate_Description")]
	public partial class RealEstate_Description
	{
		
		private int _id;
		
		private System.Nullable<int> _real_estate_id;
		
		private string _overview_conveniences;
		
		private string _distances;
		
		public RealEstate_Description()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_real_estate_id", DbType="Int")]
		public System.Nullable<int> real_estate_id
		{
			get
			{
				return this._real_estate_id;
			}
			set
			{
				if ((this._real_estate_id != value))
				{
					this._real_estate_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overview_conveniences", DbType="NVarChar(300)")]
		public string overview_conveniences
		{
			get
			{
				return this._overview_conveniences;
			}
			set
			{
				if ((this._overview_conveniences != value))
				{
					this._overview_conveniences = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distances", DbType="NVarChar(300)")]
		public string distances
		{
			get
			{
				return this._distances;
			}
			set
			{
				if ((this._distances != value))
				{
					this._distances = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User
	{
		
		private int _id;
		
		private string _user_name;
		
		private string _password;
		
		private string _email;
		
		private string _sdt;
		
		public User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(20)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this._sdt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
